{ ... }:
{
    imports = [
        ./btop.nix
        ./caffeine.nix
        ./cava.nix
        ./fastfetch
        ./git.nix
        ./hyprland
        ./hyprlock
        ./hyprpaper
        ./ollama.nix
        ./jetbrains-toolbox.nix
        ./kitty.nix
        ./mako.nix
        ./neovim.nix
        ./niri
        ./rofi.nix
        ./rofimoji.nix
        ./starship.nix
        ./thunar.nix
        ./thunderbird.nix
        ./vscode.nix
        ./waybar.nix
        ./yazi.nix
        ./zathura.nix
        ./zoxide.nix
        ./zsh.nix
    ];
}